/**
 * Copyright 2019 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

output "project_id" {
  description = "Name of the project in which test fixtures were created. The test suite consumes this value."
  value       = var.project_id
}

output "random_suffix" {
  description = "A random string generated by terraform to append to resource names. This helps avoid name collisions and the test suite consumes this value."
  value       = module.example.random_suffix
}

output "region" {
  description = "The region in which test fixtures were created. This is generated within the makefile and its scripts and must be passed up to the test suite for consumption."
  value       = var.region
}
